language: node_js

node_js:
    - 12

before_install:
    - chmod +x aws_credentials_travis.sh
    - ./aws_credentials_travis.sh
    - npm i -g ask-cli alexa-sdk aws-sdk bespoken-tools --save

script: #TODO
    - ask simulate -l en-US -t "file an appeal"

#after success:
#    - ask deploy