language: node_js

node_js:
    - 12

before_install:
    - chmod +x aws_credentials_travis.sh
    - ./aws_credentials_travis.sh
    - npm i -g ask-cli alexa-sdk aws-sdk bespoken-tools --save

script: #TODO
    - ask simulate -s amzn1.ask.skill.f7c7368d-2198-46f9-9426-209726afe4a4 -l en-US -t "file an appeal"

#after success:
#    - ask deploy
